# Database settings
database:
  uri: sqlite:///inverse_bias.db
  pool_size: 5
  echo: false

# News sources - each will be automatically available in the application
news_sources:
  cnn:
    url: https://www.cnn.com
    sitemap_url: https://www.cnn.com/sitemap/news.xml

  foxnews:
    url: https://www.foxnews.com
    sitemap_url: https://www.foxnews.com/sitemap.xml?type=news

  washingtonpost:
    url: https://www.washingtonpost.com
    sitemap_url: https://www.washingtonpost.com/sitemaps/news-sitemap.xml.gz

  apnews:
    url: https://www.apnews.com
    sitemap_url: https://www.apnews.com/news-sitemap-content.xml

# Subjects to track - each will be automatically used in the application
subjects:
  - trump
  - biden
  - bernie sanders
  - elon musk
  - putin
  - zelensky
  # Add new subjects here:
  # - mark zuckerberg

# Analysis settings
analysis:
  bias_threshold: 0.75
  sentiment_categories:
    - positive
    - neutral
    - negative
  llm_model: ollama/llama2

# API settings
api:
  host: 0.0.0.0
  port: 8080
  default_limit: 10
  max_limit: 100
