database:
  uri: postgresql://localhost/inversebias
  pool_size: 20
  echo: false

news_sources:
  cnn:
    url: https://www.cnn.com
    sitemap_url: https://www.cnn.com/sitemap/news.xml

  foxnews:
    url: https://www.foxnews.com
    sitemap_url: https://www.foxnews.com/sitemap.xml?type=news

  washingtonpost:
    url: https://www.washingtonpost.com
    sitemap_url: https://www.washingtonpost.com/sitemaps/news-sitemap.xml.gz

  apnews:
    url: https://www.apnews.com
    sitemap_url: https://www.apnews.com/news-sitemap-content.xml

subjects:
  - trump
  - biden
  - bernie sanders
  - elon musk
  - putin
  - zelensky


analysis:
  bias_threshold: 0.9
  sentiment_categories:
    - positive
    - neutral
    - negative
  llm_model: ollama/llama2

api:
  host: 0.0.0.0
  port: 8080
  default_limit: 10
  max_limit: 100
